server:
  port: 8071
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=UTC
    username: root
    password: 12345678
  dubbo:
    application: managerservice
    protocol:
      name: dubbo
    registry:
      address: 192.168.130.130:2181
      protocol: zookeeper
    base-package: mall