server:
  port: 8072
spring:
  dubbo:
    application: managerweb
    protocol:
      name: dubbo
    registry:
      address: 192.168.130.130:2181
      protocol: zookeeper
    base-package: mall
    consumer:
      timeout: 600000
      check: false