server:
  port: 8051
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: 12345678
  dubbo:
    application: searchservice
    protocol:
      name: dubbo
    registry:
      address: 192.168.130.130:2181
      protocol: zookeeper
    base-package: mall
  elasticsearch:
    jest:
      uris: http://192.168.130.130:9200